services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8181:80"
    volumes:
      - ./filebrowser_data:/srv  # this is the shared folder
      - ./filebrowser_config:/config  # config files
    environment:
      - PUID=1000  # adjust based on your system user id
      - PGID=1000  # adjust based on your system group id
    restart: unless-stopped
